image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - coverage/

test:
  stage: build
  script:
    - npm install
    - npx hardhat coverage

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv coverage public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH