image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - coverage/
    - artifacts/
    - types/

compile:
  stage: build
  script:
    - yarn
    - yarn hardhat compile

lint:
  stage: test
  script:
    - yarn lint

test:
  stage: test
  script:
    - yarn hardhat coverage
    - COINMARKETCAP_KEY=$COINMARKETCAP_KEY yarn test # gas report

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv coverage public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
