image: node:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/
    - coverage/
    - artifacts/
    - types/
    - gas-report/

compile:
  stage: build
  script:
    - yarn
    - yarn hardhat compile

lint:
  stage: test
  script:
    - yarn lint

coverage:
  stage: test
  script:
    - yarn hardhat coverage

gas-report:
  stage: test
  script:
    - mkdir gas-report
    - COINMARKETCAP_KEY=$COINMARKETCAP_KEY yarn test # gas report
    - echo "<pre>" > gas-report/index.html
    - yarn --silent ansi-to-html gas-report/index.txt --fg black --bg white >> gas-report/index.html

pages:
  stage: deploy
  script:
    - rm -rf public
    - mv coverage public
    - mv gas-report public/gas-report
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
